# Generated by Django 4.0.3 on 2022-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_image_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_pic.jpeg', null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_pic.jpeg', null=True, upload_to='mediafiles/'),
        ),
    ]
